### ISSUE TITLE
Add more web-mail domains

### ISSUE THREAD

**Issue by qurbat** [jace/mxsniff#10]
Would including a larger list of domain names be useful? This one includes some non-common web-mail providers as well: https://gist.github.com/tbrianjones/5992856/

**Comment by jace** [comment]
I combed several of these lists before making mxsniff. Many of those domains are expired. Targeting MX providers instead of actual domains seems to be far more sustainable. Data on more providers is welcome.

**Comment by jace** [comment]
Previously: https://github.com/hasgeek/baseframe/issues/170
